"""Country detection: which countries a mention is ABOUT (not where the outlet is).

ISO3 code -> names/aliases in English, French, Spanish and Arabic.
Focused on countries with UN field presence; add more as needed.
"""
COUNTRIES: dict[str, list[str]] = {
    "AFG": ["Afghanistan", "Afganistán", "أفغانستان", "Kabul"],
    "BFA": ["Burkina Faso", "بوركينا فاسو", "Ouagadougou"],
    "BDI": ["Burundi", "بوروندي"],
    "CMR": ["Cameroon", "Cameroun", "Camerún", "الكاميرون"],
    "CAF": ["Central African Republic", "République centrafricaine", "Centrafrique", "República Centroafricana", "جمهورية أفريقيا الوسطى", "Bangui"],
    "TCD": ["Chad", "Tchad", "تشاد", "N'Djamena"],
    "COL": ["Colombia", "Colombie", "كولومبيا", "Bogotá", "Bogota"],
    "COD": ["Democratic Republic of the Congo", "DR Congo", "DRC", "RDC", "République démocratique du Congo", "República Democrática del Congo", "الكونغو الديمقراطية", "Kinshasa", "Goma", "North Kivu", "Nord-Kivu"],
    "EGY": ["Egypt", "Égypte", "Egipto", "مصر", "Cairo"],
    "ETH": ["Ethiopia", "Éthiopie", "Etiopía", "إثيوبيا", "Addis Ababa", "Tigray"],
    "HTI": ["Haiti", "Haïti", "Haití", "هايتي", "Port-au-Prince"],
    "IRQ": ["Iraq", "Irak", "العراق", "Baghdad"],
    "IRN": ["Iran", "Irán", "إيران", "Tehran"],
    "ISR": ["Israel", "Israël", "إسرائيل"],
    "PSE": ["Gaza", "West Bank", "Palestine", "Cisjordanie", "Cisjordania", "غزة", "فلسطين", "الضفة الغربية"],
    "JOR": ["Jordan", "Jordanie", "Jordania", "الأردن", "Amman"],
    "KEN": ["Kenya", "Kenia", "كينيا", "Nairobi"],
    "LBN": ["Lebanon", "Liban", "Líbano", "لبنان", "Beirut", "Beyrouth"],
    "LBY": ["Libya", "Libye", "Libia", "ليبيا", "Tripoli"],
    "MLI": ["Mali", "مالي", "Bamako"],
    "MRT": ["Mauritania", "Mauritanie", "موريتانيا"],
    "MEX": ["Mexico", "Mexique", "México", "المكسيك"],
    "MOZ": ["Mozambique", "موزمبيق", "Cabo Delgado"],
    "MMR": ["Myanmar", "Birmanie", "Burma", "ميانمار"],
    "NER": ["Niger", "النيجر", "Niamey"],
    "NGA": ["Nigeria", "Nigéria", "نيجيريا", "Abuja", "Borno"],
    "PAK": ["Pakistan", "Pakistán", "باكستان", "Islamabad"],
    "PHL": ["Philippines", "Filipinas", "الفلبين", "Mindanao"],
    "RUS": ["Russia", "Russie", "Rusia", "روسيا"],
    "SAU": ["Saudi Arabia", "Arabie saoudite", "Arabia Saudita", "السعودية"],
    "SOM": ["Somalia", "Somalie", "الصومال", "Mogadishu", "Mogadiscio"],
    "SSD": ["South Sudan", "Soudan du Sud", "Sudán del Sur", "جنوب السودان", "Juba"],
    "SDN": ["Sudan", "Soudan", "Sudán", "السودان", "Khartoum", "Darfur"],
    "SYR": ["Syria", "Syrie", "Siria", "سوريا", "Damascus", "Damas"],
    "TUR": ["Turkey", "Türkiye", "Turquie", "Turquía", "تركيا"],
    "UKR": ["Ukraine", "Ucrania", "أوكرانيا", "Kyiv", "Kiev"],
    "VEN": ["Venezuela", "فنزويلا", "Caracas"],
    "YEM": ["Yemen", "Yémen", "اليمن", "Sanaa", "Sana'a", "Aden"],
    "USA": ["United States", "États-Unis", "Estados Unidos", "الولايات المتحدة", "New York"],
    "CHE": ["Switzerland", "Suisse", "Suiza", "سويسرا", "Geneva", "Genève", "Ginebra"],
    "AUT": ["Austria", "Autriche", "النمسا", "Vienna", "Vienne"],
    "GBR": ["United Kingdom", "Royaume-Uni", "Reino Unido", "المملكة المتحدة"],
    "FRA": ["France", "Francia", "فرنسا"],
    "ESP": ["Spain", "Espagne", "España", "إسبانيا"],
    "ITA": ["Italy", "Italie", "Italia", "إيطاليا"],
    "DEU": ["Germany", "Allemagne", "Alemania", "ألمانيا"],
    "BRA": ["Brazil", "Brésil", "Brasil", "البرازيل"],
    "IND": ["India", "Inde", "الهند"],
    "CHN": ["China", "Chine", "الصين"],
    "BGD": ["Bangladesh", "بنغلاديش", "Cox's Bazar"],
    "RWA": ["Rwanda", "Ruanda", "رواندا"],
    "UGA": ["Uganda", "Ouganda", "أوغندا"],
    "ZAF": ["South Africa", "Afrique du Sud", "Sudáfrica", "جنوب أفريقيا"],
    "SEN": ["Senegal", "Sénégal", "السنغال", "Dakar"],
    "CIV": ["Côte d'Ivoire", "Ivory Coast", "Costa de Marfil", "ساحل العاج"],
    "GTM": ["Guatemala", "غواتيمالا"],
    "HND": ["Honduras", "هندوراس"],
    "ECU": ["Ecuador", "Équateur", "الإكوادور"],
    "PER": ["Peru", "Pérou", "Perú", "بيرو"],
    "ARM": ["Armenia", "Arménie", "أرمينيا"],
    "AZE": ["Azerbaijan", "Azerbaïdjan", "Azerbaiyán", "أذربيجان"],
    "GEO": ["Georgia", "Géorgie", "جورجيا"],
    "TJK": ["Tajikistan", "Tadjikistan", "طاجيكستان"],
    "KGZ": ["Kyrgyzstan", "Kirghizistan", "قيرغيزستان"],
    "TUN": ["Tunisia", "Tunisie", "Túnez", "تونس"],
    "DZA": ["Algeria", "Algérie", "Argelia", "الجزائر"],
    "MAR": ["Morocco", "Maroc", "Marruecos", "المغرب"],
    "ERI": ["Eritrea", "Érythrée", "إريتريا"],
    "DJI": ["Djibouti", "Yibuti", "جيبوتي"],
    "GIN": ["Guinea", "Guinée", "غينيا"],
    "SLE": ["Sierra Leone", "سيراليون"],
    "LBR": ["Liberia", "Libéria", "ليبيريا"],
    "MDG": ["Madagascar", "مدغشقر"],
    "ZWE": ["Zimbabwe", "زيمبابوي"],
    "PRK": ["North Korea", "Corée du Nord", "Corea del Norte", "كوريا الشمالية"],
    "LKA": ["Sri Lanka", "سريلانكا"],
    "NPL": ["Nepal", "Népal", "نيبال"],
    "IDN": ["Indonesia", "Indonésie", "إندونيسيا"],
    "THA": ["Thailand", "Thaïlande", "Tailandia", "تايلاند", "Bangkok"],
    "CYP": ["Cyprus", "Chypre", "Chipre", "قبرص"],
    "SRB": ["Kosovo", "Serbia", "Serbie", "كوسوفو", "صربيا"],
    "BIH": ["Bosnia", "Bosnie", "البوسنة"],
}

# Names that are also common words / ambiguous — require exact case match
CASE_SENSITIVE = {"Chad", "Niger", "Georgia", "Jordan", "Guinea", "Turkey", "DRC", "RDC", "Aden"}
